# Generated by Django 5.1.1 on 2025-01-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articleskill',
            constraint=models.UniqueConstraint(fields=('article', 'skill'), name='unique_article_skill'),
        ),
        migrations.AddConstraint(
            model_name='courseskill',
            constraint=models.UniqueConstraint(fields=('course', 'skill'), name='unique_course_skill'),
        ),
        migrations.AddConstraint(
            model_name='joboccupation',
            constraint=models.UniqueConstraint(fields=('job', 'occupation'), name='unique_job_occupation'),
        ),
        migrations.AddConstraint(
            model_name='jobskill',
            constraint=models.UniqueConstraint(fields=('job', 'skill'), name='unique_job_skill'),
        ),
        migrations.AddConstraint(
            model_name='lawpolicyskill',
            constraint=models.UniqueConstraint(fields=('law_policy', 'skill'), name='unique_law_policy_skill'),
        ),
        migrations.AddConstraint(
            model_name='lawpublicationskill',
            constraint=models.UniqueConstraint(fields=('law_publication', 'skill'), name='unique_law_publication_skill'),
        ),
        migrations.AddConstraint(
            model_name='organizationskill',
            constraint=models.UniqueConstraint(fields=('organization', 'skill'), name='unique_organization_skill'),
        ),
        migrations.AddConstraint(
            model_name='profileskill',
            constraint=models.UniqueConstraint(fields=('profile', 'skill'), name='unique_profile_skill'),
        ),
        migrations.AddConstraint(
            model_name='projectskill',
            constraint=models.UniqueConstraint(fields=('project', 'skill'), name='unique_project_skill'),
        ),
    ]
