# Generated by Django 5.1.5 on 2025-02-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_articleskill_unique_article_skill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='creation_date',
            new_name='last_updated_at',
        ),
    ]
