# Generated by Django 5.1.5 on 2025-02-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_creation_date_course_last_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='last_updated_at',
            new_name='last_updated',
        ),
    ]
